name: em-test-go

services:
  app:
    container_name: em-test-go_app
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      GIN_MODE: release
    ports:
      - "${APP_PORT}:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: em-test-go_postgres
    image: postgres:16.3
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_LOCATION}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
